# Edit this configuration file to define what should be installed on
# your system.  Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running ‘nixos-help’).

{ config, pkgs, modulesPath, ... }:

{
  imports =
    [
      # Include the default lxd configuration.
      "${modulesPath}/virtualisation/lxc-container.nix"
      # Include the container-specific autogenerated configuration.
      ./lxd.nix
      # Include the OrbStack-specific configuration.
      ./orbstack.nix
    ];
  nix.settings.experimental-features=[ "nix-command" "flakes"];
  environment.systemPackages = with pkgs; [
git
vim
wget
curl
];
environment.variables.EDITOR = "vim";

  users.users.wicsp = {
    uid = 501;
    extraGroups = [ "wheel" ];

    # simulate isNormalUser, but with an arbitrary UID
    isSystemUser = true;
    group = "users";
    createHome = true;
    home = "/home/wicsp";
    homeMode = "700";
    useDefaultShell = true;
  };
  nix.settings = {
    substituters = [
      "https://mirror.sjtu.edu.cn/nix-channels/store"
      "https://cache.nixos.org"
    ];
  };

  security.sudo.wheelNeedsPassword = false;

  # This being `true` leads to a few nasty bugs, change at your own risk!
  users.mutableUsers = false;

  time.timeZone = "Asia/Shanghai";

  networking = {
    dhcpcd.enable = false;
    useDHCP = false;
    useHostResolvConf = false;
  };

  systemd.network = {
    enable = true;
    networks."50-eth0" = {
      matchConfig.Name = "eth0";
      networkConfig = {
        DHCP = "ipv4";
        IPv6AcceptRA = true;
      };
      linkConfig.RequiredForOnline = "routable";
    };
  };

  # Extra certificates from OrbStack.
  security.pki.certificates = [
    ''
      -----BEGIN CERTIFICATE-----
MIIEYDCCA0igAwIBAgIJAN6k1fozz56eMA0GCSqGSIb3DQEBCwUAMHwxCzAJBgNV
BAYTAkNOMRIwEAYDVQQIEwlndWFuZ2RvbmcxETAPBgNVBAcTCHNoZW56aGVuMSIw
IAYDVQQKExlTYW5nZm9yIFRlY2hub2xvZ2llcyBJbmMuMSIwIAYDVQQLExlTYW5n
Zm9yIFRlY2hub2xvZ2llcyBJbmMuMCAXDTE3MDQyNzE1MjcxOVoYDzIxMTcwNDAz
MTUyNzE5WjB8MQswCQYDVQQGEwJDTjESMBAGA1UECBMJZ3Vhbmdkb25nMREwDwYD
VQQHEwhzaGVuemhlbjEiMCAGA1UEChMZU2FuZ2ZvciBUZWNobm9sb2dpZXMgSW5j
LjEiMCAGA1UECxMZU2FuZ2ZvciBUZWNobm9sb2dpZXMgSW5jLjCCASIwDQYJKoZI
hvcNAQEBBQADggEPADCCAQoCggEBAOhIli3++Brs1tZznZFFW5FzRSV4zASWtBCg
X3CxK+OqfMDRu41d5+EbQVjp20PwuIZO9Ozg34AcliQNLaB2uRW8YWWhD/g915WJ
YcYPcEcNjcFDiZVJHMaWk8uYZSw8j6B8HSAjj88OVlFZznfQ95HcEDH0dtu4DxO3
6pZ8iQGxvxN+l2xaN3VM7ih0Qt3lP197ftmkZLgodGNOe/n7qVBM8pcRFTCXOqi/
wKLUhQ77WfBPiHW9zegnY2Mtlvk/s/Bmisv5gbRIPZDLkg9PJAPeQi6qhkHs89uN
/trltli/tK25xRrElAkr/j2RkA7YODXKPHI9F5YvwrY8T60Qh8MCAwEAAaOB4jCB
3zAdBgNVHQ4EFgQU3cTVlAH4e3VFV6i+XrOsRhu4urMwga8GA1UdIwSBpzCBpIAU
3cTVlAH4e3VFV6i+XrOsRhu4urOhgYCkfjB8MQswCQYDVQQGEwJDTjESMBAGA1UE
CBMJZ3Vhbmdkb25nMREwDwYDVQQHEwhzaGVuemhlbjEiMCAGA1UEChMZU2FuZ2Zv
ciBUZWNobm9sb2dpZXMgSW5jLjEiMCAGA1UECxMZU2FuZ2ZvciBUZWNobm9sb2dp
ZXMgSW5jLoIJAN6k1fozz56eMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQELBQAD
ggEBAJPVZg3O0bnEma3x3gdFd7Lw54LcfIeIifvR5p9M30ELZkAI3MS4z0rdXzU6
X8dTpvwyM12zcMv1PQFD0a8zYFrW6truILpUXiOJ1oHftv3N0o+WeRp5JgGmg/YP
vlvCTiwZwM//3Fx3fAo0AHhxPhrel4F4yKtVKYZWrScRC4855957i+Q4jzNFDQqY
W9rcUwj6DHeF/tLN2E8qwJm7zeaqnEXLK8OcMTfguDBdJe0cTrvLaMk0jON6ZZ+U
7jb5hjH3vKyF6YlVzYtvro66Ht8Csv6QnaGdG73UEpuxjvxvC/LjFAm+b/Ds9EDq
3lE2kA02228ATbXpGNfbzk6W3DI=
-----END CERTIFICATE-----

    ''
  ];

  # This option defines the first version of NixOS you have installed on this particular machine,
  # and is used to maintain compatibility with application data (e.g. databases) created on older NixOS versions.
  #
  # Most users should NEVER change this value after the initial install, for any reason,
  # even if you've upgraded your system to a new NixOS release.
  #
  # This value does NOT affect the Nixpkgs version your packages and OS are pulled from,
  # so changing it will NOT upgrade your system - see https://nixos.org/manual/nixos/stable/#sec-upgrading for how
  # to actually do that.
  #
  # This value being lower than the current NixOS release does NOT mean your system is
  # out of date, out of support, or vulnerable.
  #
  # Do NOT change this value unless you have manually inspected all the changes it would make to your configuration,
  # and migrated your data accordingly.
  #
  # For more information, see `man configuration.nix` or https://nixos.org/manual/nixos/stable/options#opt-system.stateVersion .
  system.stateVersion = "24.05"; # Did you read the comment?
}
