# Rime schema
# encoding: utf-8
# CC-BY-4.0

schema:
  schema_id: easy_en
  name: '智能英文'
  version: "0.9.1"
  author:
    - Patrick <ipatrickmac@gmail.com>
    - BlindingDark <blindingdark@outlook.com>
  description:
    智能英文

__include: tiger:/emoji_filter                 # Emoji 滤镜
__include: tiger:/cn_en_filter                 # 中英滤镜

easy_en:
  split_sentence: true

switches:
  - name: ascii_mode
    reset: 0
    states: [ ASCII-OFF, ASCII-ON ]

engine:
  processors:
    - ascii_composer
    - key_binder
    - speller
    - recognizer
    - punctuator
    - selector
    - navigator
    - express_editor
  segmentors:
    - matcher
    - ascii_segmentor
    - abc_segmentor
    - punct_segmentor
    - fallback_segmentor
  translators:
    - table_translator
    - punct_translator
  filters:
    - simplifier@chinese_english
    - uniquifier
    - lua_filter@*hertz.easy_en*enhance_filter

speller:
  alphabet: zyxwvutsrqponmlkjihgfedcbaZYXWVUTSRQPONMLKJIHGFEDCBA
  delimiter: " '"

translator:
  dictionary: easy_en
  user_dict: easy_en
  enable_sentence: true
  enable_encoder: false
  encode_commit_history: false
  enable_completion: true
  enable_user_dict: false
  preedit_format:
    - xlit|_| |
  comment_format:
    - xlit|~| |

key_binder:
  import_preset: default
  custom_bindings:
    __append:
      # 在這裏添加只在本方案中生效的按鍵綁定
  bindings:
    __patch:
      - tiger:/keys/page_up_down
      - tiger:/keys/selector
      - tiger:/keys/options_toggle

recognizer:
  import_preset: default
  patterns:
    uppercase: ''
