# Rime dictionary: fast_symbol
# encoding: utf-8
# CC-BY-4.0

---
name: fast_symbol
version: "2.0"
sort: original
  
columns:
  - text
  - code
  - weight
#  - stem
#encoder:
#  rules:
#    - length_equal: 2
#      formula: "AaAbBaBb"
#    - length_equal: 3
#      formula: "AaBaCaCb"
#    - length_in_range: [4, 99]
#      formula: "AaBaCaZa"
...

#下面每行前面的#号是注释符，被注释的内容=不存在
#若想采用下面被注释的举例，将前面的#号去掉，即可生效


#----------符号区----------#
#用分号引导，可一键上屏的标点，可自己改
#格式是：标点+tab+分号字母

#----------标点符号 快符----------#
# 第一排
：“	;q
？	;w
（	;e
）	;r
→	;t
·	;y
~	;u
——	;i
〖	;o
〗	;p

# 第二排
！	;a
……	;s
、	;d
“	;f
”	;g
『	;h
』	;j
￥	;k
%	;l
：	;
；	;

# 第三排
|	;z
【	;x
】	;c
《	;v
》	;b
「	;n
」	;m

#----------其他符号----------#



#----------单字降重区----------#
#通过加 回头码、容错码、自定码，来降低重码
#具体说明可看下面的网址
# https://publish.obsidian.md/csj-obsidian/1+-+Archives/Input+Method/%E8%99%8E%E7%A0%81/%E7%94%A8%E6%88%B7%E8%87%AA%E5%AE%9A%E4%BC%98%E5%8C%96%E6%80%9D%E8%B7%AF%E5%BB%BA%E8%AE%AE

#----------回头码----------#
#回取首根小码来降重

#沓	kors	1000
#麂	xojl	1000


#----------容错码----------#
#顺取前四根，不跳码

#蠃	fdvc	100
#榖	gwfe	100

#----------容错码----------#
#用户自定，示例为 补音
#汩kor+g (gǔ)，汨kor+m (mì)

#汩	korg	100
#汨	korm	100


#----------修改字频、简码----------#
#格式：字+tab+编码+tab+字频
#例如：将“阳”作为2简，代替原来的“费”，“阳”的字频必须比“费”高
#阳的全码重码——“衵”，也可提至首选，降重


#阳	to	100000000000
#衵	tor	100000000000

#字频可被重置，写在这里的优先级高于主码表
#字频若想置顶，可直接加超大的权重值100000000000……
#字频若想置后，常用字集的最小字频是255，改成这个就会在常用字集的最后
#若需精准调控，可在“tiger.dict.yaml”文件中搜索，找到具体数值
#例如 想把 “凫” 改到 “麂” 前面，但不能在 “秃” 前面
#“秃”的字频 查得为5592，“麂”的字频，查得为519

#凫	xoj	500
#麂	xoj	100
#叆	bywr	10000000000

#可以加些自定的多重简码，下面已分好区域

#的	u	10359470
#一	f	4346343
#是	o	3240478
#不	c	3217018
#了	r	3211043
#在	n	2565479
#我	t	2302420
#人	j	2289348
#大	m	1442576
#中	d	1344335
#来	a	1313926
#和	x	1215893
#说	s	1214559
#为	i	1195466
#到	y	1172915
#就	g	1135253
#也	e	1093918
#要	v	991671
#可	z	952249
#道	h	911043
#而	l	824737
#得	w	796166
#能	k	781343
#都	q	651479
#如	b	613530
#行	p	586170

#----------一简多重----------#
！	a
》	b
〉	b
】	c
〕	c
、	d
|	d
（	e
“	f
‘	f
”	g
’	g
『	h
——	i
—	i
』	j
￥	k
$	k
%	l
」	m
「	n
〖	o
〗	p
：“	q
#：‘	q
）	r
……	s
…	s
→	t
~	u
《	v
〈	v
？	w
【	x
〔	x
·	y

# 来了	a
# 如果	b
# 不是	c
# 中间	d
# 也许	e
# 一点	f
# 就是	g
# 道理	h
# 为啥	i
# 人才	j
# 能力	k
# 而且	l
# 大哥	m
# 在于	n
# 是的	o
# 行走	p
# 都是	q
# 了解	r
# 说话	s
# 我的	t
# 的确	u
# 要求	v
# 得到	w
# 和气	x
# 到达	y
# 可以	z


#----------二简多重----------#

#准	wu

#----------三简多重----------#

#羸	fdv

#----------无码加词_全码词----------#
#支持无码加词，但只能用标准打词法，即：四码全码打出来

#彳亍	p	100
#虎码输入法
#秃码输入法


#----------有码加词_简词----------#
#若想加些简词，二码，三码即可出字，需加上编码

#无语	ds
#搞快点	uhy


## 注：上面的词，若想调整词序，再后面加个tab，再加词频即可


#----------增加单字----------#
#虎码是全字集，收字量近10W，一般无需加单字
#不过虎码以下几个汉字分区没有收，可自行添加
#汉字的Unicode分区说明可看下面的网址
# https://unicode-table.com/cn/blocks/

#----------部首补充----------#

#----------康熙部首----------#

#----------兼容字----------#

#----------兼补字----------#

#----------注音----------#

#----------其他分区----------#

#----------虎码字根----------#
疒	]ab	2
𤕫	]ab	1
⽧	]ab	0
丁	]ad	1
	]ad	0
㇆	]ae	62
乛	]ae	61
⺂	]ae	60
乚	]ae	59
⺃	]ae	58
⺄	]ae	57
く	]ae	56
の	]ae	55
フ	]ae	54
レ	]ae	53
ヿ	]ae	52
ㄅ	]ae	51
ㄋ	]ae	50
ㄑ	]ae	49
ㄟ	]ae	48
ㄣ	]ae	47
ㄥ	]ae	46
㇁	]ae	45
㇂	]ae	44
㇃	]ae	43
㇄	]ae	42
㇅	]ae	41
㇇	]ae	40
㇈	]ae	39
㇉	]ae	38
㇊	]ae	37
㇋	]ae	36
㇌	]ae	35
㇍	]ae	34
㇎	]ae	33
㇕	]ae	32
㇖	]ae	31
㇗	]ae	30
㇙	]ae	29
㇛	]ae	28
㇜	]ae	27
㇝	]ae	26
㇞	]ae	25
㇟	]ae	24
㇡	]ae	23
㇢	]ae	22
乁	]ae	21
	]ae	20
	]ae	19
𠃊	]ae	18
𠃋	]ae	17
𠃌	]ae	16
𠃍	]ae	15
𠃑	]ae	14
𠄌	]ae	13
𠄎	]ae	12
𡿨	]ae	11
𪛙	]ae	10
乁	]ae	9
り	]ae	8
	]ae	7
	]ae	6
	]ae	5
ㆴ	]ae	4
ㆹ	]ae	3
	]ae	2
	]ae	1
	]ae	0
丰	]af	13
龶	]af	12
	]af	11
	]af	10
丯	]af	9
	]af	8
	]af	7
	]af	6
	]af	5
缶	]af	4
	]af	3
𦈢	]af	2
𬼈	]af	1
⽸	]af	0
鬼	]ag	3
⻤	]ag	2
	]ag	1
⿁	]ag	0
乙	]ai	8
㇠	]ai	7
𠃉	]ai	6
⼄	]ai	5
	]ai	4
	]ai	3
𬼂	]ai	2
	]ai	1
ㆸ	]ai	0
六	]al	7
六	]al	6
	]al	5
	]al	4
耒	]al	3
	]al	2
𦓤	]al	1
⽾	]al	0
门	]am	8
⻔	]am	7
門	]am	6
𨳇	]am	5
𨳈	]am	4
	]am	3
⾨	]am	2
皿	]am	1
⽫	]am	0
片	]ap	16
爿	]ap	15
丬	]ap	14
	]ap	13
	]ap	12
	]ap	11
	]ap	10
	]ap	9
	]ap	8
	]ap	7
⺦	]ap	6
	]ap	5
	]ap	4
	]ap	3
	]ap	2
⽙	]ap	1
⽚	]ap	0
舌	]as	2
	]as	1
⾆	]as	0
未	]aw	0
弓	]bg	5
	]bg	4
𢎗	]bg	3
𢎜	]bg	2
𢎧	]bg	1
⼸	]bg	0
乂	]bi	6
㐅	]bi	5
	]bi	4
〤	]bi	3
ㄨ	]bi	2
ㆫ	]bi	1
ㆼ	]bi	0
彐	]bj	15
𫜹	]bj	14
⺔	]bj	13
⺕	]bj	12
ㅌ	]bj	11
彑	]bj	10
	]bj	9
	]bj	8
	]bj	7
𰀂	]bj	6
	]bj	5
	]bj	4
	]bj	3
𬼖	]bj	2
𰀄	]bj	1
⼹	]bj	0
	]bk	5
	]bk	4
	]bk	3
	]bk	2
𠂎	]bk	1
𠂑	]bk	0
卵	]bl	0
面	]bm	9
靣	]bm	8
⾯	]bm	7
卯	]bm	6
	]bm	5
丣	]bm	4
戼	]bm	3
	]bm	2
𬻇	]bm	1
𫝁	]bm	0
女	]bn	1
⼥	]bn	0
氏	]bs	1
⽒	]bs	0
聿	]bv	9
肀	]bv	8
⺺	]bv	7
⺻	]bv	6
	]bv	5
	]bv	4
	]bv	3
	]bv	2
𦘒	]bv	1
⾀	]bv	0
云	]by	5
	]by	4
𠫓	]by	3
	]by	2
	]by	1
ㄊ	]by	0
不	]cb	2
𣎴	]cb	1
	]cb	0
虫	]cc	2
	]cc	1
⾍	]cc	0
飞	]cf	4
⻜	]cf	3
飛	]cf	2
𩙱	]cf	1
⾶	]cf	0
古	]cg	0
火	]ch	10
灬	]ch	9
⺣	]ch	8
	]ch	7
	]ch	6
	]ch	5
	]ch	4
	]ch	3
	]ch	2
	]ch	1
⽕	]ch	0
支	]ci	1
⽀	]ci	0
及	]cj	2
	]cj	1
及	]cj	0
尸	]cs	8
ㄕ	]cs	7
	]cs	6
	]cs	5
	]cs	4
𠃜	]cs	3
𡰣	]cs	2
	]cs	1
⼫	]cs	0
业	]cy	8
	]cy	7
	]cy	6
	]cy	5
𠁁	]cy	4
	]cy	3
	]cy	2
	]cy	1
	]cy	0
口	]dk	6
〇	]dk	5
	]dk	4
㇣	]dk	3
	]dk	2
ㅒ	]dk	1
⼝	]dk	0
里	]dl	2
	]dl	1
⾥	]dl	0
民	]dm	2
	]dm	1
⺠	]dm	0
黾	]dm	5
黽	]dm	4
㫣	]dm	3
黾	]dm	2
⻪	]dm	1
⿌	]dm	0
无	]du	5
⺛	]du	4
兂	]du	3
	]du	2
旡	]du	1
⽆	]du	0
由	]dy	1
甴	]dy	0
干	]eg	3
	]eg	2
チ	]eg	1
⼲	]eg	0
见	]ej	5
見	]ej	4
⻅	]ej	3
⾒	]ej	2
	]ej	1
	]ej	0
木	]em	4
朩	]em	3
𣎳	]em	2
	]em	1
⽊	]em	0
欠	]eq	1
⽋	]eq	0
彡	]es	5
	]es	4
	]es	3
〃	]es	2
𰀪	]es	1
⼺	]es	0
𠂉	]et	1
	]et	0
穴	]ex	5
	]ex	4
	]ex	3
𠕉	]ex	2
𥤢	]ex	1
⽳	]ex	0
也	]ey	0
㡀	]fb	3
	]fb	2
	]fb	1
	]fb	0
辰	]fc	6
𠩐	]fc	5
𨑃	]fc	4
𨑄	]fc	3
𫝕	]fc	2
𮝾	]fc	1
⾠	]fc	0
骨	]fg	10
⾻	]fg	9
⻣	]fg	8
	]fg	7
冎	]fg	6
	]fg	5
	]fg	4
	]fg	3
	]fg	2
	]fg	1
	]fg	0
一	]fi	4
㇀	]fi	3
㇐	]fi	2
⼀	]fi	1
ㆪ	]fi	0
且	]fq	2
	]fq	1
𠀇	]fq	0
示	]fs	12
礻	]fs	11
	]fs	10
⺬	]fs	9
	]fs	8
⺭	]fs	7
	]fs	6
	]fs	5
𥘅	]fs	4
𱍐	]fs	3
⽰	]fs	2
	]fs	1
	]fs	0
亡	]fw	4
亾	]fw	3
兦	]fw	2
	]fw	1
	]fw	0
歹	]gd	8
⺞	]gd	7
歺	]gd	6
	]gd	5
𣦵	]gd	4
	]gd	3
	]gd	2
𣦶	]gd	1
⽍	]gd	0
高	]gg	9
	]gg	8
	]gg	7
	]gg	6
	]gg	5
髙	]gg	4
	]gg	3
	]gg	2
	]gg	1
⾼	]gg	0
句	]gj	0
士	]gs	10
⼠	]gs	9
丨	]gs	8
亅	]gs	7
	]gs	6
ㄧ	]gs	5
㇑	]gs	4
⼁	]gs	3
㇚	]gs	2
⼅	]gs	1
ㆳ	]gs	0
土	]gt	2
	]gt	1
⼟	]gt	0
韦	]gw	4
韋	]gw	3
𮧮	]gw	2
⻙	]gw	1
⾱	]gw	0
羊	]gy	14
⺶	]gy	13
⺷	]gy	12
	]gy	11
𦍌	]gy	10
芈	]gy	9
⺸	]gy	8
羋	]gy	7
𦍋	]gy	6
	]gy	5
𢆉	]gy	4
	]gy	3
	]gy	2
𦍍	]gy	1
⽺	]gy	0
八	]hb	19
丷	]hb	18
	]hb	17
䒑	]hb	16
	]hb	15
	]hb	14
	]hb	13
癶	]hb	12
	]hb	11
	]hb	10
	]hb	9
𭼽	]hb	8
	]hb	7
	]hb	6
	]hb	5
	]hb	4
⼋	]hb	3
⽨	]hb	2
ㅈ	]hb	1
ㆿ	]hb	0
夫	]hf	0
谷	]hg	6
	]hg	5
	]hg	4
	]hg	3
𠔌	]hg	2
𧮫	]hg	1
⾕	]hg	0
子	]hi	7
⼦	]hi	6
夂	]hi	5
夊	]hi	4
	]hi	3
ㄆ	]hi	2
⼡	]hi	1
⼢	]hi	0
攵	]hp	3
攴	]hp	2
⺙	]hp	1
⽁	]hp	0
壴	]hu	1
	]hu	0
心	]hx	6
忄	]hx	5
⺗	]hx	4
㣺	]hx	3
𢖩	]hx	2
⺖	]hx	1
⼼	]hx	0
册	]ic	9
冊	]ic	8
	]ic	7
𠕁	]ic	6
	]ic	5
	]ic	4
	]ic	3
𠕋	]ic	2
	]ic	1
𠕋	]ic	0
丶	]id	6
㇏	]id	5
㇔	]id	4
乀	]id	3
	]id	2
	]id	1
⼂	]id	0
艮	]ig	4
	]ig	3
⾉	]ig	2
	]ig	1
	]ig	0
丩	]ij	6
ㄐ	]ij	5
	]ij	4
𠂈	]ij	3
	]ij	2
	]ij	1
ㆢ	]ij	0
立	]il	3
	]il	2
	]il	1
⽴	]il	0
舟	]io	2
	]io	1
⾈	]io	0
糸	]is	8
	]is	7
纟	]is	6
⺯	]is	5
⺰	]is	4
糹	]is	3
	]is	2
	]is	1
⽷	]is	0
予	]iv	1
𠄔	]iv	0
乡	]ix	0
幺	]iy	4
ㄠ	]iy	3
⺓	]iy	2
⼳	]iy	1
ㆯ	]iy	0
斗	]jd	3
鬥	]jd	2
⽃	]jd	1
⾾	]jd	0
亼	]ji	3
亽	]ji	2
	]ji	1
𠓛	]ji	0
仑	]jl	1
侖	]jl	0
人	]jr	6
亻	]jr	5
⺅	]jr	4
𠆢	]jr	3
	]jr	2
⼈	]jr	1
	]jr	0
豕	]js	6
	]js	5
𬺻	]js	4
𧰧	]js	3
𧰨	]js	2
豕	]js	1
⾗	]js	0
入	]ju	1
⼊	]ju	0
寸	]kc	1
⼨	]kc	0
亥	]kh	0
㠯	]ki	3
𤕪	]ki	2
㠯	]ki	1
	]ki	0
九	]kj	0
母	]km	1
⺟	]km	0
水	]ks	27
氵	]ks	26
⺡	]ks	25
⺍	]ks	24
氺	]ks	23
⺢	]ks	22
	]ks	21
	]ks	20
	]ks	19
	]ks	18
	]ks	17
	]ks	16
	]ks	15
	]ks	14
	]ks	13
	]ks	12
𣱱	]ks	11
𭕄	]ks	10
ツ	]ks	9
	]ks	8
⽔	]ks	7
厶	]ks	6
ㄙ	]ks	5
龴	]ks	4
	]ks	3
	]ks	2
	]ks	1
⼛	]ks	0
毋	]ku	4
毌	]ku	3
	]ku	2
𣫬	]ku	1
⽏	]ku	0
艹	]lc	24
⺾	]lc	23
丌	]lc	22
廾	]lc	21
丱	]lc	20
	]lc	19
卝	]lc	18
⺿	]lc	17
⻀	]lc	16
艸	]lc	15
卄	]lc	14
	]lc	13
廾	]lc	12
⼶	]lc	11
⾋	]lc	10
齿	]lc	9
歯	]lc	8
齒	]lc	7
𠚒	]lc	6
𣥫	]lc	5
𣦋	]lc	4
𦥒	]lc	3
⻭	]lc	2
⻮	]lc	1
⿒	]lc	0
而	]le	1
⽽	]le	0
方	]lf	1
⽅	]lf	0
廿	]ln	3
龷	]ln	2
𠥻	]ln	1
	]ln	0
千	]lq	1
	]lq	0
卅	]ls	7
	]ls	6
丗	]ls	5
𠀍	]ls	4
	]ls	3
生	]ls	2
𤯓	]ls	1
⽣	]ls	0
卌	]lx	10
	]lx	9
	]lx	8
𬻂	]lx	7
𠦜	]lx	6
	]lx	5
夕	]lx	4
	]lx	3
	]lx	2
	]lx	1
⼣	]lx	0
牙	]ly	3
㸦	]ly	2
⽛	]ly	1
	]ly	0
巴	]mb	6
	]mb	5
𢀳	]mb	4
	]mb	3
	]mb	2
	]mb	1
	]mb	0
大	]md	1
⼤	]md	0
二	]me	6
𠄞	]me	5
𠄟	]me	4
𠄠	]me	3
⼆	]me	2
	]me	1
	]me	0
光	]mg	1
	]mg	0
户	]mh	9
戶	]mh	8
戸	]mh	7
	]mh	6
	]mh	5
	]mh	4
𠁣	]mh	3
𠃛	]mh	2
	]mh	1
⼾	]mh	0
豸	]mi	2
	]mi	1
⾘	]mi	0
冂	]mk	14
凵	]mk	13
⺆	]mk	12
	]mk	11
ㄇ	]mk	10
ㄩ	]mk	9
𫡃	]mk	8
	]mk	7
	]mk	6
	]mk	5
	]mk	4
𠙴	]mk	3
凵	]mk	2
⼌	]mk	1
⼐	]mk	0
两	]ml	5
兩	]ml	4
両	]ml	3
㒳	]ml	2
	]ml	1
兩	]ml	0
犬	]mq	4
犭	]mq	3
⺨	]mq	2
	]mq	1
⽝	]mq	0
石	]ms	1
⽯	]ms	0
甫	]nf	1
	]nf	0
鬲	]ng	6
⿀	]ng	5
	]ng	4
	]ng	3
	]ng	2
	]ng	1
	]ng	0
黄	]nh	3
黃	]nh	2
⻩	]nh	1
⿈	]nh	0
勹	]nk	12
⼓	]nk	11
ㆠ	]nk	10
匚	]nk	9
⼖	]nk	8
コ	]nk	7
	]nk	6
ユ	]nk	5
	]nk	4
ㄈ	]nk	3
匸	]nk	2
𠥓	]nk	1
⼕	]nk	0
马	]nm	8
⻢	]nm	7
⾺	]nm	6
ㄢ	]nm	5
馬	]nm	4
	]nm	3
	]nm	2
𢎘	]nm	1
𫠉	]nm	0
十	]ns	10
𬺰	]ns	9
	]ns	8
𠂇	]ns	7
	]ns	6
𬂛	]ns	5
⼗	]ns	4
	]ns	3
	]ns	2
	]ns	1
ㆺ	]ns	0
戊	]nu	3
戉	]nu	2
	]nu	1
	]nu	0
王	]nw	4
⺩	]nw	3
𤣩	]nw	2
	]nw	1
王	]nw	0
辛	]nx	4
	]nx	3
	]nx	2
𨐋	]nx	1
⾟	]nx	0
贝	]ob	3
⻉	]ob	2
貝	]ob	1
⾙	]ob	0
川	]oc	13
	]oc	12
	]oc	11
	]oc	10
	]oc	9
巛	]oc	8
巜	]oc	7
〣	]oc	6
ㄍ	]oc	5
⼮	]oc	4
𡿦	]oc	3
𫶧	]oc	2
ㆣ	]oc	1
ㆻ	]oc	0
自	]oi	1
⾃	]oi	0
几	]oj	6
⺇	]oj	5
𠘨	]oj	4
	]oj	3
𠘧	]oj	2
	]oj	1
⼏	]oj	0
日	]or	7
曰	]or	6
⺜	]or	5
ㄖ	]or	4
	]or	3
𫩏	]or	2
⽇	]or	1
⽈	]or	0
矢	]os	1
⽮	]os	0
尤	]oy	6
尢	]oy	5
⺐	]oy	4
ㄤ	]oy	3
𡯁	]oy	2
尢	]oy	1
⼪	]oy	0
长	]pc	9
長	]pc	8
镸	]pc	7
⻑	]pc	6
⻒	]pc	5
⻓	]pc	4
	]pc	3
𨱗	]pc	2
𨱘	]pc	1
⾧	]pc	0
刀	]pd	17
刂	]pd	16
⺉	]pd	15
〢	]pd	14
リ	]pd	13
ㄉ	]pd	12
	]pd	11
	]pd	10
	]pd	9
	]pd	8
	]pd	7
	]pd	6
	]pd	5
	]pd	4
	]pd	3
𠚣	]pd	2
⼑	]pd	1
ㆵ	]pd	0
儿	]pe	6
	]pe	5
	]pe	4
	]pe	3
	]pe	2
ㄦ	]pe	1
⼉	]pe	0
戈	]pg	4
	]pg	3
	]pg	2
𭠍	]pg	1
⼽	]pg	0
黑	]ph	3
黒	]ph	2
𪐗	]ph	1
⿊	]ph	0
弋	]pi	3
	]pi	2
𫠠	]pi	1
⼷	]pi	0
臼	]pj	5
⺽	]pj	4
	]pj	3
𦥑	]pj	2
⾅	]pj	1
⾅	]pj	0
米	]pm	3
𠂭	]pm	2
	]pm	1
⽶	]pm	0
鼠	]ps	5
⿏	]ps	4
䑕	]ps	3
鼡	]ps	2
	]ps	1
	]ps	0
足	]pu	3
⻊	]pu	2
𧾷	]pu	1
⾜	]pu	0
行	]px	1
⾏	]px	0
走	]pz	2
赱	]pz	1
⾛	]pz	0
臣	]qc	10
𦣞	]qc	9
	]qc	8
𦣝	]qc	7
	]qc	6
𮍌	]qc	5
	]qc	4
	]qc	3
	]qc	2
	]qc	1
⾂	]qc	0
耳	]qe	2
㔿	]qe	1
⽿	]qe	0
井	]qj	1
	]qj	0
老	]ql	3
⺹	]ql	2
⽼	]ql	1
耂	]ql	0
目	]qm	2
	]qm	1
⽬	]qm	0
牛	]qn	6
⺧	]qn	5
牜	]qn	4
𠂒	]qn	3
⽜	]qn	2
	]qn	1
	]qn	0
齐	]qq	9
⻬	]qq	8
斉	]qq	7
⻫	]qq	6
齊	]qq	5
	]qq	4
𠫸	]qq	3
𠫼	]qq	2
𪗄	]qq	1
⿑	]qq	0
食	]qs	10
饣	]qs	9
飠	]qs	8
⻝	]qs	7
⻞	]qs	6
⻟	]qs	5
	]qs	4
	]qs	3
𩙿	]qs	2
⻠	]qs	1
⾷	]qs	0
田	]qt	1
⽥	]qt	0
非	]rf	6
	]rf	5
𠂼	]rf	4
𩇦	]rf	3
𩇧	]rf	2
𩇨	]rf	1
⾮	]rf	0
之	]ri	0
巾	]rj	4
	]rj	3
	]rj	2
⼱	]rj	1
ㆬ	]rj	0
囗	]rk	1
⼞	]rk	0
了	]rl	1
𠄏	]rl	0
皮	]rp	2
	]rp	1
⽪	]rp	0
七	]rq	4
	]rq	3
	]rq	2
ㆤ	]rq	1
ㆥ	]rq	0
殳	]rs	1
⽎	]rs	0
竹	]ru	6
⺮	]ru	5
	]ru	4
	]ru	3
	]ru	2
𥫗	]ru	1
⽵	]ru	0
瓦	]rw	1
⽡	]rw	0
又	]ry	5
ス	]ry	4
ㄡ	]ry	3
	]ry	2
	]ry	1
⼜	]ry	0
屮	]sc	7
	]sc	6
	]sc	5
𡳾	]sc	4
	]sc	3
	]sc	2
屮	]sc	1
⼬	]sc	0
各	]sg	0
止	]si	13
	]si	12
龰	]si	11
	]si	10
	]si	9
	]si	8
	]si	7
	]si	6
𱤻	]si	5
	]si	4
	]si	3
	]si	2
𣥂	]si	1
⽌	]si	0
甲	]sj	1
曱	]sj	0
力	]sl	2
ㄌ	]sl	1
⼒	]sl	0
尚	]ss	3
	]ss	2
龸	]ss	1
尙	]ss	0
言	]sy	7
讠	]sy	6
⻈	]sy	5
訁	]sy	4
𧥛	]sy	3
𧥜	]sy	2
⾔	]sy	1
	]sy	0
阝	]te	2
⻏	]te	1
⻖	]te	0
弗	]tf	7
𢎨	]tf	6
	]tf	5
𠂔	]tf	4
	]tf	3
𪩲	]tf	2
	]tf	1
	]tf	0
革	]tg	1
⾰	]tg	0
衣	]ti	11
衤	]ti	10
⻂	]ti	9
	]ti	8
𧘇	]ti	7
	]ti	6
	]ti	5
	]ti	4
𱍸	]ti	3
	]ti	2
衣	]ti	1
⾐	]ti	0
斤	]tj	3
	]tj	2
	]tj	1
⽄	]tj	0
龙	]tl	7
竜	]tl	6
	]tl	5
龍	]tl	4
	]tl	3
⿓	]tl	2
⻰	]tl	1
⻯	]tl	0
丿	]tp	3
㇒	]tp	2
㇓	]tp	1
⼃	]tp	0
三	]ts	6
疋	]ts	5
⺪	]ts	4
𤴔	]ts	3
𤴓	]ts	2
	]ts	1
⽦	]ts	0
雨	]tv	13
⻗	]tv	12
	]tv	11
	]tv	10
	]tv	9
	]tv	8
	]tv	7
	]tv	6
𠕒	]tv	5
𠕘	]tv	4
𠕲	]tv	3
𮦄	]tv	2
𮦆	]tv	1
⾬	]tv	0
用	]ty	5
	]ty	4
	]ty	3
𤰃	]ty	2
	]ty	1
⽤	]ty	0
白	]ub	1
⽩	]ub	0
辶	]uc	6
⻎	]uc	5
辵	]uc	4
	]uc	3
⻍	]uc	2
⾡	]uc	1
⻌	]uc	0
工	]ug	4
	]ug	3
𪛜	]ug	2
⼯	]ug	1
ㆲ	]ug	0
隹	]ui	1
⾫	]ui	0
手	]us	18
扌	]us	17
⺘	]us	16
キ	]us	15
龵	]us	14
	]us	13
𰀁	]us	12
	]us	11
	]us	10
	]us	9
	]us	8
𠀆	]us	7
	]us	6
	]us	5
	]us	4
	]us	3
	]us	2
	]us	1
⼿	]us	0
廴	]uy	1
⼵	]uy	0
匕	]vb	7
	]vb	6
	]vb	5
	]vb	4
	]vb	3
𠤎	]vb	2
⼔	]vb	1
	]vb	0
已	]vi	0
己	]vj	3
	]vj	2
	]vj	1
⼰	]vj	0
㐄	]vk	6
ヰ	]vk	5
	]vk	4
	]vk	3
	]vk	2
𡕒	]vk	1
𫝀	]vk	0
毛	]vm	7
も	]vm	6
	]vm	5
	]vm	4
	]vm	3
𣬛	]vm	2
⽑	]vm	1
	]vm	0
乃	]vn	2
	]vn	1
	]vn	0
气	]vq	2
	]vq	1
⽓	]vq	0
禸	]vr	1
⽱	]vr	0
山	]vs	5
⼭	]vs	4
巳	]vs	3
⺒	]vs	2
	]vs	1
	]vs	0
文	]vw	1
⽂	]vw	0
西	]vx	7
⻄	]vx	6
覀	]vx	5
⻃	]vx	4
襾	]vx	3
	]vx	2
	]vx	1
⾑	]vx	0
月	]vy	18
⺝	]vy	17
	]vy	16
⺼	]vy	15
冃	]vy	14
	]vy	13
円	]vy	12
	]vy	11
	]vy	10
	]vy	9
𱼀	]vy	8
	]vy	7
	]vy	6
	]vy	5
	]vy	4
𠔼	]vy	3
	]vy	2
	]vy	1
⽉	]vy	0
乍	]wa	0
冫	]wb	7
⺀	]wb	6
゛	]wb	5
	]wb	4
	]wb	3
	]wb	2
	]wb	1
⼎	]wb	0
彳	]wc	3
亍	]wc	2
ㄔ	]wc	1
⼻	]wc	0
冖	]wg	16
宀	]wg	15
	]wg	14
⼍	]wg	13
⼧	]wg	12
龟	]wg	11
⻱	]wg	10
⻲	]wg	9
⻳	]wg	8
亀	]wg	7
龜	]wg	6
𪚦	]wg	5
𪚴	]wg	4
𪛉	]wg	3
𬹝	]wg	2
⿔	]wg	1
	]wg	0
兔	]wt	7
兎	]wt	6
	]wt	5
	]wt	4
	]wt	3
	]wt	2
𠮥	]wt	1
兔	]wt	0
五	]wu	0
鱼	]wv	5
⻥	]wv	4
魚	]wv	3
𩵋	]wv	2
	]wv	1
⿂	]wv	0
象	]wx	2
	]wx	1
𧰼	]wx	0
页	]wy	6
⻚	]wy	5
頁	]wy	4
	]wy	3
	]wy	2
𩑋	]wy	1
⾴	]wy	0
厂	]xc	5
⺁	]xc	4
ㄏ	]xc	3
𠂆	]xc	2
⼚	]xc	1
ㆷ	]xc	0
⺈	]xd	4
𠂊	]xd	3
	]xd	2
ク	]xd	1
	]xd	0
广	]xg	2
⼴	]xg	1
ㄬ	]xg	0
禾	]xh	4
	]xh	3
𥝌	]xh	2
⽲	]xh	1
	]xh	0
鹿	]xl	4
	]xl	3
	]xl	2
	]xl	1
⿅	]xl	0
鸟	]xn	6
⻦	]xn	5
鳥	]xn	4
	]xn	3
	]xn	2
𫠓	]xn	1
⿃	]xn	0
束	]xs	0
乌	]xu	2
烏	]xu	1
	]xu	0
音	]xy	1
⾳	]xy	0
爪	]ya	9
𤓰	]ya	8
⽖	]ya	7
⺤	]ya	6
⺥	]ya	5
爫	]ya	4
	]ya	3
𱬴	]ya	2
	]ya	1
𫜵	]ya	0
卜	]yb	11
⺊	]yb	10
ㅑ	]yb	9
	]yb	8
	]yb	7
	]yb	6
	]yb	5
𰀠	]yb	4
	]yb	3
	]yb	2
𠁡	]yb	1
⼘	]yb	0
车	]yc	4
⻋	]yc	3
車	]yc	2
	]yc	1
⾞	]yc	0
瓜	]yg	1
⽠	]yg	0
至	]yi	2
	]yi	1
⾄	]yi	0
曲	]yq	1
𡆪	]yq	0
四	]ys	10
罒	]ys	9
⺫	]ys	8
⺲	]ys	7
⺵	]ys	6
䍏	]ys	5
𠁤	]ys	4
𠃢	]ys	3
𦉭	]ys	2
	]ys	1
𪛘	]ys	0
小	]yx	6
⺌	]yx	5
	]yx	4
𡭔	]yx	3
	]yx	2
	]yx	1
⼩	]yx	0
酉	]yy	2
𮠕	]yy	1
⾣	]yy	0
豆	]zd	1
⾖	]zd	0
甘	]zg	7
	]zg	6
	]zg	5
𠀠	]zg	4
𤮺	]zg	3
𭺪	]zg	2
𭺫	]zg	1
⽢	]zg	0
虎	]zh	10
虍	]zh	9
	]zh	8
	]zh	7
	]zh	6
	]zh	5
	]zh	4
	]zh	3
𮓗	]zh	2
⾌	]zh	1
⻁	]zh	0
金	]zj	20
钅	]zj	19
⻐	]zj	18
釒	]zj	17
	]zj	16
𨤾	]zj	15
	]zj	14
𨥀	]zj	13
⾦	]zj	12
卩	]zj	11
⺋	]zj	10
㔾	]zj	9
卪	]zj	8
	]zj	7
	]zj	6
	]zj	5
ㄗ	]zj	4
	]zj	3
𠁾	]zj	2
⼙	]zj	1
ㆡ	]zj	0
可	]zk	1
	]zk	0
麻	]zm	2
麻	]zm	1
⿇	]zm	0
身	]zs	6
㐆	]zs	5
𠂣	]zs	4
𨈏	]zs	3
𨈐	]zs	2
𨈑	]zs	1
⾝	]zs	0
亠	]zt	3
〦	]zt	2
⼇	]zt	1
	]zt	0
羽	]zv	5
	]zv	4
羽	]zv	3
	]zv	2
𦏲	]zv	1
⽻	]zv	0
习	]zx	2
	]zx	1
	]zx	0
