# Rime schema
# encoding: utf-8
# CC-BY-4.0

schema:
  schema_id: fast_symbol
  name: 快符（勿用）
  version: "2024-10-31"
  description: 用于词典部署（不用勾选）

engine:
  translators:
    - table_translator

translator:
  dictionary: fast_symbol
  enable_user_dict: false
  enable_sentence: false
  enable_encoder: false

key_binder:
  import_preset: default
  custom_bindings:
    __append:
      # 在這裏添加只在本方案中生效的按鍵綁定
  bindings:
    __patch:
      - tiger:/keys/page_up_down
      - tiger:/keys/selector
      - tiger:/keys/options_toggle