distribution_code_name: Squirrel
distribution_name: "鼠鬚管"
distribution_version: 1.0.3
install_time: "Wed Feb 12 15:05:32 2025"
installation_id: "2a44650b-916f-42ec-b296-d3b020fecfd1"
rime_version: 1.13.0