# Rime schema
# encoding: utf-8
# CC-BY-4.0

schema:
  schema_id: japanese
  name: 日本語ローマ字
  version: "2024.11.12"
  author:
    - Hertz Hwang <hertz@26hz.com.cn>

switches:
  - name: ascii_mode
    reset: 0
    states: [ 假名, 西文 ]
  - name: half_shape
    states: [ 半角, 全角 ]
    reset: 0

engine:
  processors:
    - ascii_composer
    - recognizer
    - key_binder
    - speller
    - punctuator
    - selector
    - navigator
    - express_editor
  segmentors:
    - ascii_segmentor
    - matcher
    - abc_segmentor
    - punct_segmentor
    - fallback_segmentor
  translators:
    - punct_translator
    - script_translator
  filters:
    - uniquifier

speller:
  alphabet: 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ-_'
  delimiter: " '"

translator:
  dictionary: japanese
  __include: tiger:/dict_All_false

key_binder:
  import_preset: default
  custom_bindings:
    __append:
      # 在這裏添加只在本方案中生效的按鍵綁定
  bindings:
    __patch:
      - tiger:/keys/page_up_down
      - tiger:/keys/selector
      - tiger:/keys/options_toggle

__include: tiger:/rec

punctuator:
  import_preset: default
  full_shape: &symbols
    '.': 。
    ',': 、
    '/': ・
  half_shape: *symbols
