# Rime dictionary: tiger_phrase_ice
# encoding: utf-8
# CC-BY-4.0

---
name: tiger_phrase_ice
version: "2.0"
sort: by_weight
import_tables:
  - dicts/tiger_core        # 官方虎词11w+单字
  - dicts/ice.base
  - dicts/ice.ext
  - dicts/ice.others
  - dicts/ice.tencent
  - dicts/kaomoji           # Vv进入Kaomoji颜表情
  
columns:
  - text
  - code
  - weight
  - stem

...
