# Rime schema settings
# encoding: utf-8
# CC-BY-4.0

schema:
  schema_id: tiger_spelling_pseudo
  name: 虎码·伪方案·勿用勿改
  version: "2024.11.28"
  author:
    - 發明人 徐国银先生
    - Hertz Hwang <hertz@26hz.com.cn>
  description: |
    伪方案，不能打字。
    不要选我，不要修改本方案及配套词典。
    仅用于辅助三重注解方案实现注解功能。

translator:
  dictionary: tiger_spelling_pseudo
  enable_user_dict: false
