# Rime schema
# encoding: utf-8
# CC-BY-4.0

schema:
  author:
    - Hertz Hwang <hertz@26hz.com.cn>
  dependencies:
    - charset
    - pinyin
    - fast_symbol
    - tiger_spelling_pseudo
    - radical_flypy
    - easy_en
    - japanese
    - tiger_codes
    - tiger_oni
    - tiger_phrase
  description: |
    🐯·单·五二顶
  name: "🐯·单·五二顶"
  schema_id: tiger_code_52p
  version: "2024-12-14"

__patch:
  - tiger_code_52p.custom:/patch?
  - engine/processors/@before 4: lua_processor@*hertz.key_binder
  - engine/processors/@before 5: lua_processor@*hertz.popping
  - engine/filters/@next: simplifier@chinese_english

__include: tiger:/switches_engine_table        # Rime模块
__include: tiger:/fast_symbol_translator       # 快符
__include: tiger:/easy_en_translator           # 英文
__include: tiger:/japanese_translator          # 日文
__include: tiger:/radical_flypy_translator     # 部件拆字
__include: tiger:/tiger_codes_translator       # 官方虎词
__include: tiger:/tiger_oni_translator         # 九重鬼虎
__include: tiger:/tiger_phrase_translator      # 赫兹虎单整句
__include: tiger:/tiger_phrases_translator     # 官方虎词整句
__include: tiger:/reverse_lookup_translator_xh # 小鹤反查
__include: tiger:/s2t_filter                   # 简繁滤镜
__include: tiger:/history_filter               # z 键历史
__include: tiger:/emoji_filter                 # Emoji 滤镜
__include: tiger:/cn_en_filter                 # 中英滤镜
__include: tiger:/mars_filter                  # 火星文滤镜
__include: tiger:/embeded_cands_filter         # 候选嵌入
__include: tiger:/hertz                        # Hertz定制

speller:
  #auto_clear: max_length
  #auto_select: true
  max_code_length: 4
  popping:
    - match: "[a-z]{4}"
      accept: "[^ 2345]"
      prefix: 2
  alphabet: "qwertyuoipasdfghjklzxcvbnm@"
  #auto_select_pattern: ^;.$ # |^\w{4}$
  algebra:
    __patch:
      - tiger:/algebra/core        # 核心拼算
  #    #- tiger:/algebra/wildcard?   # 通配拼算
  #    - tiger:/algebra/erase       # 擦除编码

translator:
  dictionary: tiger_code
  enable_user_dict: false
  enable_charset_filter: true
  enable_encoder: true
  enable_sentence: false
  encode_commit_history: true
  enable_completion: true

key_binder:
  import_preset: default
  custom_bindings:
    __append:
      # 在這裏添加只在本方案中生效的按鍵綁定
  popping:
    #- match: "[a-z]{4}"
    #  accept: "j"
    #  send_sequence: "{Left}{Left}{Left}{space}{space}"
    #- match: "[a-z]{4}"
    #  accept: "k"
    #  send_sequence: "{Left}{Left}{space}{space}"
    #- match: "[a-z]{4}"
    #  accept: "l"
    #  send_sequence: "{Left}{space}{space}"
    #- when: has_menu
    #  accept: ;
    #  send: '2'
    #- when: has_menu
    #  accept: "'"
    #  send: '3'
    #- when: has_menu
    #  accept: "["
    #  send: '4'
    #- when: has_menu
    #  accept: "]"
    #  send: '5'
  bindings:
    __patch:
      - :/key_binder/custom_bindings?
      - tiger:/keys/emacs_mode
      - tiger:/keys/tab
      - tiger:/keys/page_up_down
      - tiger:/keys/selector
      - tiger:/keys/options_toggle

__include: tiger:/rec

punctuator:
  #import_preset:
  __include: tiger:/punctuator

# 默认启用语言模型
__include: tiger:/octagram/enable_for_tiger
# 若要禁用，可直接注释掉上面的 __include

tiger_spelling:
  lua:
    switch_key: "Control+c"
    cycle_key: "Shift+Control+C"
schema_name:
  spelling: tiger_spelling_pseudo
  code: tiger_code_52p