# Rime dictionary: tiger_phrase_chord
# encoding: utf-8
# CC-BY-4.0

---
name: tiger_phrase_chord
version: "2025-01-01"
sort: original
import_tables:
  - dicts/hertz_tiger_chord   # 虎码11w+单字
...

# 单次一简字
的	"U_
一	"F_
是	"O_
不	"C_
了	"R_
在	"N_
我	"T_
人	"J_
大	"M_
中	"D_
来	"A_
和	"X_
说	"S_
为	"I_
到	"Y_
就	"G_
也	"E_
要	"V_
可	"Z_
道	"H_
而	"L_
得	"W_
能	"K_
都	"Q_
如	"B_
行	"P_
的	"_U
一	"_F
是	"_O
不	"_C
了	"_R
在	"_N
我	"_T
人	"_J
大	"_M
中	"_D
来	"_A
和	"_X
说	"_S
为	"_I
到	"_Y
就	"_G
也	"_E
要	"_V
可	"_Z
道	"_H
而	"_L
得	"_W
能	"_K
都	"_Q
如	"_B
行	"_P

1	"a_
2	"s_
3	"d_
4	"f_
5	"g_
6	"q_
7	"w_
8	"e_
9	"r_
0	"t_
1	"_a
2	"_s
3	"_d
4	"_f
5	"_g
6	"_q
7	"_w
8	"_e
9	"_r
0	"_t

# 左手上屏小写
a	A_
b	B_
c	C_
d	D_
e	E_
f	F_
g	G_
h	H_
i	I_
j	J_
k	K_
l	L_
m	M_
n	N_
o	O_
p	P_
q	Q_
r	R_
s	S_
t	T_
u	U_
v	V_
w	W_
x	X_
y	Y_
z	Z_
# 右手上屏大写
A	_A
B	_B
C	_C
D	_D
E	_E
F	_F
G	_G
H	_H
I	_I
J	_J
K	_K
L	_L
M	_M
N	_N
O	_O
P	_P
Q	_Q
R	_R
S	_S
T	_T
U	_U
V	_V
W	_W
X	_X
Y	_Y
Z	_Z
#左符号
,	,_
.	._
!	!_
?	?_
:	:_
;	;_
'	'_
@	@_
$	$_
/	/_
\	\_
[	[_
]	]_
(	(_
)	)_
<	<_
>	>_
{	{_
}	}_
=	=_
-	-_
~	~_
|	|_
*	*_
+	+_
&	&_
#	#_
%	%_
`	`_
^	^_
#右符号
，	_,
。	_.
！	_!
？	_?
：	_:
；	_;
‘	_'
℃	_@
¥	_$
“	_/
”	_\
【	_[
】	_]
（	_(
）	_)
《	_<
》	_>
｛	_{
｝	_}
≠	_=
—	_-
～	_~
’	_|
×	_*
÷	_+
§	_&
、	_#
‰	_%
·	_`
…	_^
